test:
  name: "Payment Simulation"
  description: "This benchmark scenario will use ppa transactions, to generate a database to analize bond value."
  workers:
    type: local
    number: 1
  rounds:
    - label: writepayments
      txNumber: 500
      rateControl:
        type: fixed-rate
        opts:
          tps: 15
      callback: benchmarks/callbacks/ppa/payment/payment.js
      arguments:
        minterOrg: farmer
        invokerMspId: farmerMSP
        client: farmer-client-1
        endorser1Org: originator
        endorser2Org: aggregator
        endorser3Org: spv
        depositReference: deposito123211
        depositBank: Banco123
observer:
  type: local
  interval: 1
monitor:
  interval: 1
  type: ["docker"]
  docker:
    containers: ["all"]
